name: Package Managers

on:
  workflow_dispatch:
  push:

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Git
      env:
        SSH_CONFIG: ${{ vars.SSH_CONFIG }}
        PRIVATE_PERSONAL: ${{ secrets.PRIVATE_PERSONAL }}
        PRIVATE_AUR: ${{ secrets.PRIVATE_AUR }}
      run: |
        set -euo pipefail

        git config --global user.name "Matthew Wilding"
        git config --global user.email "mbwilding@gmail.com"

        ssh_path="$HOME/.ssh"
        install -d -m 700 "$ssh_path"

        # Write SSH configuration and keys securely using printf
        printf "%s" "$SSH_CONFIG" > "$ssh_path/config"
        chmod 600 "$ssh_path/config"

        printf "%s" "$PRIVATE_PERSONAL" > "$ssh_path/personal"
        chmod 600 "$ssh_path/personal"

        printf "%s" "$PRIVATE_AUR" > "$ssh_path/aur"
        chmod 600 "$ssh_path/aur"

    # - name: Clone
    #   env:
    #     GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
    #   run: |
    #     git clone --depth 1 aur@aur.archlinux.org:ttf-neospleen.git
    #     git clone --depth 1 aur@aur.archlinux.org:ttf-neospleen-nerd-font.git

    - name: Homebrew
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        set -e

        git clone --depth 1 git@github.com:mbwilding/homebrew-neospleen.git
        cd homebrew-neospleen

        # You might uncomment version check if needed
        # if [ -z "$VERSION" ]; then
        #   echo "Error: VERSION environment variable is not set."
        #   exit 1
        # fi
        VERSION="1.0.57"

        neospleen_path="Casks/font-neospleen.rb"
        neospleen_url="https://github.com/mbwilding/NeoSpleen/releases/download/${VERSION}/NeoSpleen-TTF.zip"

        neospleen_nerd_path="Casks/font-neospleen-nerd-font.rb"
        neospleen_nerd_url="https://github.com/mbwilding/NeoSpleen/releases/download/${VERSION}/NeoSpleenNerdFont-TTF.zip"

        process_file () {
            file=$1
            url=$2

            echo "Processing: $file"

            echo "Downloading: ${url}"
            temp_zip="/tmp/artifact.zip"
            http_status=$(curl -L -s -w "%{http_code}" -o "$temp_zip" "$url")
            if [ "$http_status" != "200" ]; then
              echo "Error: Expected HTTP 200 but got $http_status"
              exit 1
            fi

            echo "Generating SHA256"
            sha256=$(sha256sum "$temp_zip" | awk '{print $1}')
            echo "$sha256"

            rm "$temp_zip"

            sed -i "s|version \"[^\"]*\"|version \"$VERSION\"|" "$file"
            sed -i "s|sha256 \"[^\"]*\"|sha256 \"$sha256\"|" "$file"
        }

        process_file "$neospleen_path" "$neospleen_url"
        process_file "$neospleen_nerd_path" "$neospleen_nerd_url"

        git add .
        git commit -m "Updated to version: $VERSION"
        git push
