name: Package Managers

on:
  workflow_dispatch:
  push:

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Git
      env:
        SSH_CONFIG: ${{ vars.SSH_CONFIG }}
        PRIVATE_PERSONAL: ${{ secrets.PRIVATE_PERSONAL }}
        PRIVATE_AUR: ${{ secrets.PRIVATE_AUR }}
      run: |
        set -euo pipefail

        ssh_path="$HOME/.ssh"
        install -d -m 700 "$ssh_path"

        # Write SSH configuration and keys securely using printf
        printf "%s" "$SSH_CONFIG" > "$ssh_path/config"
        chmod 600 "$ssh_path/config"

        printf "%s" "$PRIVATE_PERSONAL" > "$ssh_path/personal"
        chmod 600 "$ssh_path/personal"

        printf "%s" "$PRIVATE_AUR" > "$ssh_path/aur"
        chmod 600 "$ssh_path/aur"

    - name: Clone
      run: |
        git clone --depth 1 git@github.com:mbwilding/homebrew-neospleen.git
        ls homebrew-neospleen
        # git clone --depth 1 aur@aur.archlinux.org:ttf-neospleen.git
        # git clone --depth 1 aur@aur.archlinux.org:ttf-neospleen-nerd-font.git
