name: Release

on:
  push:
    branches:
      - dev

env:
  FONT_NAME: NeoSpleen

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Read current version from file
      id: read_version
      run: |
        VERSION=$(grep -oP 'Version: "\K[^"]+' $FONT_NAME.sfd)
        echo "::set-output name=version::$VERSION"
    - name: Increment version
      id: increment_version
      run: |
        OLD_VERSION=${{ steps.read_version.outputs.version }}
        MAJOR=$(echo $OLD_VERSION | cut -d'.' -f1)
        MINOR=$(echo $OLD_VERSION | cut -d'.' -f2)
        PATCH=$(echo $OLD_VERSION | cut -d'.' -f3)
        PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH.$GITHUB_RUN_NUMBER"
        echo "::set-output name=new_version::$NEW_VERSION"
    - name: Replace version in file
      run: |
        sed -i "s/Version: \"${{ steps.read_version.outputs.version }}\"/Version: \"${{ steps.increment_version.outputs.new_version }}\"/g" $FONT_NAME.sfd
    - name: FontForge
      run: |
        sudo apt-get install software-properties-common
        sudo add-apt-repository ppa:fontforge/fontforge
        sudo apt-get update
        sudo apt-get install fontforge
    - name: Generate
      run: |
        input="$FONT_NAME.sfd"
        output="$FONT_NAME.ttf"
        fontforge -lang=ff -c "Open(\"$input\"); Generate(\"$output\")"
    - name: NerdFont
      run: |
        wget https://github.com/ryanoasis/nerd-fonts/blob/master/FontPatcher.zip
        unzip FontPatcher.zip -d NerdFontPatcher
        outputIn="${FONT_NAME}NerdFont-Regular.ttf"
        outputOut="${FONT_NAME}-NerdFont.ttf"
        fontforge -script NerdFontPatcher/font-patcher "$output" -c --boxdrawing
        mv $outputIn $outputOut
    - name: Release
      uses: pipe-cd/actions-gh-release@v2.6.0
      with:
          release_file: "*.ttf"
          token: ${{ secrets.GITHUB_TOKEN }}
