name: Release

on:
  workflow_dispatch:

env:
  FONT_NAME: NeoSpleen

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install python3 fontforge python3-fontforge libwoff-dev
    - name: Increment Version
      id: version
      run: |
        OLD_VERSION=$(grep -oP 'Version: "\K[^"]+' ${FONT_NAME}.sfd)
        MAJOR=$(echo ${OLD_VERSION} | awk -F. '{print $1}')
        MINOR=$(echo ${OLD_VERSION} | awk -F. '{print $2}')
        NEW_VERSION="${MAJOR}.${MINOR}.${GITHUB_RUN_NUMBER}"
        sed -i "s/Version: \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/Version: \"${NEW_VERSION}\"/g" ${FONT_NAME}.sfd
        sed -i "s/Version +ACIA-[0-9]\+\.[0-9]\+\.[0-9]\+/Version +ACIA-${NEW_VERSION}/g" ${FONT_NAME}.sfd
        sed -i "s/sfntRevision: 0x000[0-9]*0000/sfntRevision: 0x000${MAJOR}0000/g" ${FONT_NAME}.sfd
        echo "version=${NEW_VERSION}" >> ${GITHUB_OUTPUT}
    - name: Generate Fonts
      run: ./generate_fonts.py
    - name: Generate Nerd Fonts
      run: ./generate_nerd_fonts.py
    - name: List Fonts
      run: ls fonts
    - name: Generate Showcases
      run: |
        pip3 install Pillow
        ./generate_showcases.py
    - name: List Showcases
      run: ls renders
    - name: Zip
      run: |
        cd fonts
        echo "Zipping Standard"
        find . -type f -name "*.ttf" ! -name "*NerdFont*" | zip "NeoSpleen-TTF.zip" -@
        echo "Zipping Nerd Font"
        find . -type f -name "*NerdFont*.ttf" | zip "NeoSpleenNerdFont-TTF.zip" -@
    - name: Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          fonts/*.ttf
          fonts/*.woff2
          fonts/*.zip
          renders/*.png
        name: ${{ steps.version.outputs.version }}
        tag_name: ${{ steps.version.outputs.version }}
