name: Release

on:
  push:
    branches:
      - main

env:
  FONT_NAME: NeoSpleen

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: FontForge
      run: sudo apt-get install fontforge
    - name: Increment Version
      id: version
      run: |
        OLD_VERSION=$(grep -oP 'Version: "\K[^"]+' ${FONT_NAME}.sfd)
        MAJOR=$(echo ${OLD_VERSION} | awk -F. '{print $1}')
        MINOR=$(echo ${OLD_VERSION} | awk -F. '{print $2}')
        NEW_VERSION="${MAJOR}.${MINOR}.${GITHUB_RUN_NUMBER}"
        sed -i "s/Version: \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/Version: \"${NEW_VERSION}\"/g" ${FONT_NAME}.sfd
        sed -i "s/Version +ACIA-[0-9]\+\.[0-9]\+\.[0-9]\+/Version +ACIA-${NEW_VERSION}/g" ${FONT_NAME}.sfd
        sed -i "s/sfntRevision: 0x000[0-9]*0000/sfntRevision: 0x000${MAJOR}0000/g" ${FONT_NAME}.sfd
        echo "version=${NEW_VERSION}" >> ${GITHUB_OUTPUT}
    - name: Generate Fonts
      run: |
        input="${FONT_NAME}.sfd"
        output="${FONT_NAME}.ttf"
        fontforge -lang=ff -c "Open(\"${input}\"); Generate(\"${output}\")"
        wget https://github.com/ryanoasis/nerd-fonts/raw/master/FontPatcher.zip
        unzip FontPatcher.zip -d NerdFontPatcher
        outputIn="${FONT_NAME}NerdFont-Regular.ttf"
        outputOut="${FONT_NAME}-NerdFont.ttf"
        fontforge -script NerdFontPatcher/font-patcher ${output} --complete --boxdrawing --no-progressbars --quiet
        mv ${outputIn} ${outputOut}
    - name: Generate Showcase
      run: |
        sudo install python3
        pip3 install Pillow
        python3 generate_image.py
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.ttf
          Showcase.png
        name: ${{ steps.version.outputs.version }}
        tag_name: ${{ steps.version.outputs.version }}
