name: Release

on:
  push:
    branches:
      - dev

env:
  FONT_NAME: NeoSpleen

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: FontForge
      run: |
        apt-get install software-properties-common
        add-apt-repository ppa:fontforge/fontforge
        apt-get update
        apt-get install fontforge
    - name: Generate
      run: |
        input="$FONT_NAME.sfd"
        output="$FONT_NAME.ttf"
        fontforge -lang=ff -c "Open(\"$input\"); Generate(\"$output\")"
    - name: NerdFont
      run: |
        wget https://github.com/ryanoasis/nerd-fonts/blob/master/FontPatcher.zip
        unzip FontPatcher.zip -d NerdFontPatcher
        outputIn="${FONT_NAME}NerdFont-Regular.ttf"
        outputOut="${FONT_NAME}-NerdFont.ttf"
        fontforge -script NerdFontPatcher/font-patcher "$output" -c --boxdrawing
        mv $outputIn $outputOut
    - name: Release
      uses: pipe-cd/actions-gh-release@v2.6.0
      with:
          release_file: "*.ttf"
          token: ${{ secrets.GITHUB_TOKEN }}
